MakingDreams\DestinationsBundle\Entity\ImagenesDestino:
    type: entity
    table: imagenes_destino
    indexes:
        id_destino:
            columns:
                - id_destino
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        imagen1:
            type: blob
            nullable: true
            length: null
            fixed: false
            comment: ''
        imagen2:
            type: blob
            nullable: true
            length: null
            fixed: false
            comment: ''
        imagen3:
            type: blob
            nullable: true
            length: null
            fixed: false
            comment: ''
    manyToOne:
        idDestino:
            targetEntity: Destino
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_destino:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
