hotels_hotelrestaurante:
    resource: "@HotelsBundle/Resources/config/routing/hotelrestaurante.yml"
    prefix:   /hotelrestaurante

hotels_homepage:
    path:     /
    defaults: { _controller: HotelsBundle:Default:showView }

hotel_page:
    path:     /hotel
    defaults: { _controller: HotelsBundle:Default:showHotel }