imagenRest:
    resource: "@RestaurantsBundle/Resources/config/routing/hotelrestaurante.yml"
    prefix:   /imagenRest
    
restaurants_homepage:
    path:     /
    defaults: { _controller: RestaurantsBundle:Default:index }
    
restaurants_detail:
    path:     /{id}/detail
    defaults: { _controller: RestaurantsBundle:Default:showRest }
    
restaurants_admin:
    path:     /admin
    defaults: { _controller: RestaurantsBundle:Default:showRestAdmin }
