package_imagen:
    resource: "@PackagesBundle/Resources/config/routing/paquete.yml"
    prefix:   /imagen
    
imagen:
    resource: "@PackagesBundle/Resources/config/routing/paquete.yml"
    prefix:   /imagen

packages_homepage:
    path:     /
    defaults: { _controller: PackagesBundle:Default:showView }

package_page:
    path:     /package
    defaults: { _controller: PackagesBundle:Default:showPackage }
    
newpackage_page:
    path:     /new
    defaults: { _controller: PackagesBundle:Default:showNewPackage }
    
editpackage_page:
    path:     /edit
    defaults: { _controller: PackagesBundle:Default:showEditPackage }
        
packages_search:
    path:     /search
    defaults: { _controller: PackagesBundle:Default:search }