configurations:
    path:   /configurations
    defaults: { _controller: ConfigurationsBundle:Default:configurations }
    
login:
    resource: "@LoginBundle/Resources/config/routing.yml"
    prefix:   /login

about:
    resource: "@AboutBundle/Resources/config/routing.yml"
    prefix:   /about

destinations:
    resource: "@DestinationsBundle/Resources/config/routing.yml"
    prefix:   /destination

hotels:
    resource: "@HotelsBundle/Resources/config/routing.yml"
    prefix:   /hotels

restaurants:
    resource: "@RestaurantsBundle/Resources/config/routing.yml"
    prefix:   /restaurants

packages:
    resource: "@PackagesBundle/Resources/config/routing.yml"
    prefix:   /packages
    
hotels_hotelrestaurante:
    resource: "@HotelsBundle/Resources/config/routing/hotelrestaurante.yml"
    prefix:   /hotelrestaurante

init:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /login
        permanent: true