destinations_destino:
    resource: "@DestinationsBundle/Resources/config/routing/destino.yml"
    prefix:   /destino

destinations_homepage:
    path:     /
    defaults: { _controller: DestinationsBundle:Default:showView }
    
destiny_detail:
    path:     /detail
    defaults: { _controller: DestinationsBundle:Default:showDetail }
