login_usuario:
    resource: "@LoginBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario

login_homepage:
    path:     /
    defaults: { _controller: LoginBundle:Default:showView }
    
log_in:
    path:     /log_in
    defaults: { _controller: LoginBundle:Default:login }
    
log_out:
    path:     /log_out
    defaults: { _controller: LoginBundle:Default:logout }