login_usuario:
    resource: "@LoginBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario

login_homepage:
    path:     /
    defaults: { _controller: LoginBundle:Default:showView }
    
loginalgo:
    path:     /cualquiera
    defaults: { _controller: LoginBundle:Default:login }