agregar_hotelrestaurante:
    path:     /{id}/agregar_hotelrestaurante
    defaults: { _controller: "RestaurantsBundle:HotelRestaurante:agregar_hotelrestaurante" }
    
hotelrestaurante:
    path:     /
    defaults: { _controller: "RestaurantsBundle:HotelRestaurante:index" }

hotelrestaurante_show:
    path:     /{id}/show
    defaults: { _controller: "RestaurantsBundle:HotelRestaurante:show" }

hotelrestaurante_new:
    path:     /new
    defaults: { _controller: "RestaurantsBundle:HotelRestaurante:new" }

hotelrestaurante_create:
    path:     /create
    defaults: { _controller: "RestaurantsBundle:HotelRestaurante:create" }
    methods:  POST

hotelrestaurante_edit:
    path:     /{id}/edit
    defaults: { _controller: "RestaurantsBundle:HotelRestaurante:edit" }

hotelrestaurante_update:
    path:     /{id}/update
    defaults: { _controller: "RestaurantsBundle:HotelRestaurante:update" }
    methods:  [POST, PUT]

hotelrestaurante_delete:
    path:     /{id}/delete
    defaults: { _controller: "RestaurantsBundle:HotelRestaurante:delete" }
    methods:  [POST, DELETE]
    
imagenRest:
    pattern: /{id}/imagenRest
    defaults: { _controller: "RestaurantsBundle:HotelRestaurante:imagenRest" }
    
