MakingDreams\PackagesBundle\Entity\HotelRestaurante:
    type: entity
    table: hotel_restaurante
    indexes:
        destino_asociado_idx:
            columns:
                - destino_asociado
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        direccion:
            type: string
            nullable: true
            length: 500
            fixed: false
            comment: ''
        servicios:
            type: string
            nullable: true
            length: 450
            fixed: false
            comment: ''
        tipo:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        direccionMapa:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: direccion_mapa
        provincia:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
    manyToOne:
        destinoAsociado:
            targetEntity: Destino
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                destino_asociado:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
